FileVersion = 1
Projects = {libui-beef = {Path = "."}, controlgallery = {Path = "examples/controlgallery"}, hello-world = {Path = "examples/hello-world"}, histogram = {Path = "examples/histogram"}}

[Workspace]
StartupProject = "hello-world"
